-- PostgreSQL database dump
\restrict generic_dump_key
SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET row_security = off;
SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TYPE public.article_state AS ENUM ('draft', 'published', 'editor''s choice');
ALTER TYPE public.article_state OWNER TO postgres;

CREATE TABLE public.authors (
    id bigint NOT NULL,
    name character varying(100) NOT NULL
);
ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);
ALTER TABLE ONLY public.authors ADD CONSTRAINT authors_pkey PRIMARY KEY (id);

CREATE TABLE public.articles (
    id bigint NOT NULL,
    author_id bigint NOT NULL,
    title character varying(255) DEFAULT 'a; title, with -- punctuation'::character varying NOT NULL,
    body text,
    state public.article_state DEFAULT 'draft'::public.article_state NOT NULL,
    active boolean DEFAULT true NOT NULL,
    score integer DEFAULT 0 NOT NULL,
    amount numeric(12,2) DEFAULT 0.00,
    ratio double precision,
    token uuid DEFAULT gen_random_uuid(),
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    bytes bytea,
    published_on date,
    starts_at time without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp with time zone,
    address inet,
    CONSTRAINT articles_score_check CHECK ((score >= 0))
);
ALTER TABLE public.articles OWNER TO postgres;
CREATE SEQUENCE public.articles_id_seq AS bigint START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER SEQUENCE public.articles_id_seq OWNER TO postgres;
ALTER SEQUENCE public.articles_id_seq OWNED BY public.articles.id;
ALTER TABLE ONLY public.articles ALTER COLUMN id SET DEFAULT nextval('public.articles_id_seq'::regclass);
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_pkey PRIMARY KEY (id);
CREATE INDEX index_articles_on_author_id ON public.articles USING btree (author_id);
CREATE UNIQUE INDEX index_articles_on_token ON public.articles USING btree (token);
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_author_fk FOREIGN KEY (author_id) REFERENCES public.authors(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE ONLY public.articles ADD CONSTRAINT articles_title_check CHECK ((length(title) > 0)) NOT VALID;
COMMENT ON TABLE public.articles IS 'Content; not a second statement';
COMMENT ON COLUMN public.articles.state IS 'Publication state';

CREATE TABLE public.schema_migrations (version character varying NOT NULL);
ALTER TABLE ONLY public.schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);
\unrestrict generic_dump_key
INSERT INTO "schema_migrations" (version) VALUES ('20260101000000');
